### ISSUE TITLE
Change Branding from Operate First to AICoE

### ISSUE THREAD

**Issue by goern** [AICoE/meteor#101]
just looking at the elyra-tutorial, we see an "Operate Firs" branded jupyterbook, as Meteor is an AICoE initiative, we should change the branding accordingly 

There is also a footer reading 'Powered by Shooting Star' which should be replaced by a AICoE branding

**Comment by isabelizimm** [comment]
Addressed [here](https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/266)
