### ISSUE TITLE
user experience: :rocket: button inside jupyterbook gives 404 error

### ISSUE THREAD

**Issue by isabelizimm** [AICoE/meteor#112]
When you click on the rocket within the JupyterBook to launch into JupyterLab, there is a 404 Error
![clickonrocket](https://user-images.githubusercontent.com/54685329/131001260-48b9c642-41e6-434e-9f13-0bb34e61c6f2.png)
![404meteor](https://user-images.githubusercontent.com/54685329/131001248-854dbb86-9db5-41fd-a5fd-b4553e962116.png)

I would like for this to launch directly into the JupyterLab instance that is created with the Meteor Webapp

**Comment by tumido** [comment]
Unless we touch the repo content we can't modify the value. Can you please check if JupyterBook can consume values via environment variables?

**Comment by isabelizimm** [comment]
Attempted to pass environment variables in the _config.yml file with no luck :(

**Comment by isabelizimm** [comment]
Looking into this more and stumbled across this piece: https://jupyterbook.org/interactive/launchbuttons.html#add-a-launch-on-jupyterhub-button

```
You can configure the location of the JupyterHub (which you may set up on your own using a guide such as [zero to jupyterhub for kubernetes](https://zero-to-jupyterhub.readthedocs.io/en/latest/) or the[ littlest jupyterhub](https://tljh.jupyter.org/en/latest/)) with the following configuration:

On your JupyterHub server, you need two dependencies installed:

1. To clone the notebook with the launch link, the server needs nbgitpuller.
2. To open myst-markdown as notebooks, the server needs jupytext>=0.16.

You can add the following line to your DockerFile:
RUN pip install jupytext nbgitpuller
```

It looks like we should be able to have a way to launch into a JupyterLab instance without needing to touch the repo.

**Comment by tumido** [comment]
Hm.. the problem with `nbgitpuller` seems that:

1. We still need to pass the JupyterHub server host url to the JupyterBook
2. JupyterHub server needs to be running (aka the pod has to be spawned by JupyterHub Spawner already)
3. Does not solve dependencies of the repo - those need to be already included in the JupyterHub server image

I think what this boils down to is that we probably need to re-think how we use JupyterHub - does it make sense to have a single generic JupyterHub image for all the repos and install all the deps on the fly (after the image is spawned) via Thoth's JH dependency resolution plugin? Just a wild though :smile:
