### ISSUE TITLE
Change button text on order page

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#113]
Should these buttons at the bottom be changed to say, "Open with JupyterHub" and "Open as JupyterBook"?
 
![image](https://user-images.githubusercontent.com/4494906/131138983-90825220-d1c2-4603-91a5-d560b483598e.png)

**Comment by tumido** [comment]
Hm.. my biggest problem with that is that "JupyterHub" and "JupyterBook" labels are visually just too similar, it's confusing... The point of good UX is that user knows "what's up" at a first glance. It's easier to differentiate "JupyterHub" and "Website" than "JupyterHub" and "JupyterBook". I wonder what can we do about it. Any suggestion?

**Comment by Shreyanand** [comment]
Suggestion: "Run code in JupyterHub" and "Read docs with JupyterBook"

**Comment by MichaelClifford** [comment]
I understand the similarity of the two words makes it tough. But I think "open as website" just struck me as a bit confusing. I like @Shreyanand 's suggestion of differentiating by the verb at the beginning. WDYT?
