### ISSUE TITLE
Internal Server Error when selecting "open as jupyterhub" 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#115]
![image](https://user-images.githubusercontent.com/4494906/131142211-6b8f08f3-468f-40a7-9a4d-fa59ad04ec2f.png)

I get the above error after shutting down my jupyterhub pod a selecting "open as jupyterhub" from the meteor order page.

**Comment by 4n4nd** [comment]
This was a known issue in Jupyterhub MOC/Zero env. Issue: https://github.com/operate-first/support/issues/365

**Comment by tumido** [comment]
Closing as duplicate of https://github.com/operate-first/support/issues/365 

Feel free to reopen if this manifests in the devconfus cluster as well.
