### ISSUE TITLE
Review CD/Elyra tutorial process and propose metrics

### ISSUE THREAD

**Issue by hemajv** [AICoE/meteor#17]
Review the CD pipeline/Elyra tutorial process and create a flowchart explaining the same identifying the components and metrics that can be measured.

### Acceptance Criteria

- [ ] #33
- [x] Identifying suitable metrics that can be measured throughout the pipeline process
- [x] Identify the data sources required for these metrics

**Comment by tumido** [comment]
Resources: https://github.com/AICoE/elyra-aidevsecops-tutorial

**Comment by hemajv** [comment]
Initial doc created [here](https://docs.google.com/document/d/1SWv29LkjKUA4rkM3V6bR6GzVWJPWMgHm-RUPH7xiPrE/edit?usp=sharing)  to map out all the steps present in the existing tutorial and include some useful metrics we can measure in each of the steps
