### ISSUE TITLE
meteor pipeline for JH image is not copying the tutorial content 

### ISSUE THREAD

**Issue by pacospace** [AICoE/meteor#200]
1. Go to https://shower.meteor.zone/
2. Insert https://github.com/AICoE/manage-dependencies-tutorial
3. open JH image

No material is available in the JH image, which is build from `BASE_IMAGE=quay.io/thoth-station/s2i-elyra-custom-notebook:v0.4.1`

**Comment by tumido** [comment]
Is this the case for this particular image only or a generic problem for all the images? I thought I've fixed it :smile: 

Related: https://github.com/AICoE/meteor/issues/125

**Comment by pacospace** [comment]
> Is this the case for this particular image only or a generic problem for all the images? I thought I've fixed it smile
> 
> Related: #125

I tested with elyra tutorial, but it fails for space on device: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/aicoe-meteor/tekton.dev~v1beta1~PipelineRun/meteor-xl6fj-jupyterhub/logs/generate
