### ISSUE TITLE
"no space left on device" error while building a meteor

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#207]
While using https://shower.meteor.zone/ to build a meteor for https://github.com/aicoe-aiops/ocp-ci-analysis, the JupyterHub build  failed (meteor-rpj9n-jupyterhub) at pipeline step "generate". Investigating the logs, I can see the following error message: 

`ERROR: An error occurred: write upload/src/data/raw/testgrid_183.json.gz: no space left on device`

What options does a user have if their repo is larger than the default device size? Can we provide some indication on the landing page about the size limits? and how to update them when needed?

**Comment by MichaelClifford** [comment]
cc: @tumido @4n4nd

**Comment by tumido** [comment]
Hey! Fix will be nontrivial at this point. We have a fixed workspace size for the builds to be 500Mi per pipeline instance. Hence bigger repositories are currently not supported. We aim to make the workspace size configurable in future update.

/kind bug
/priority imporant-soon

**Comment by tumido** [comment]
Resolved via https://github.com/AICoE/meteor-operator/pull/49 . Shower now enables to configure workspace size for each deployment. Working on deployment to prod in matter of a day. In prod we'll bump it from 500Mi to 2Gi and hope it'll be enough.
