### ISSUE TITLE
Environment Requirements should be abstracted from user

### ISSUE THREAD

**Issue by oindrillac** [AICoE/meteor#21]
We mention a bunch of "Environment Requirements" to the user [here](https://github.com/AICoE/elyra-aidevsecops-tutorial#environment-required) which are needed to run the tutorial.

All of these requirements should either be already set up for the user, hence omitted from the guide, or if the user needs to access/install something these items should point to how-to guides for them rather than wiki pages or landing pages.
 
/label shooting-star

related: https://github.com/AICoE/meteor/issues/16

**Comment by goern** [comment]
ja, from my point of view the subproject are `area`s rather than just a label

@tumido wdyt?
