### ISSUE TITLE
Training nb does not consume outputs of Download Dataset nb

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/meteor#23]
In the AI pipeline, IIUC the first step ([download_dataset.ipynb](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e033cdffeb8291be372417dd2dda819b264aba5c/notebooks/download_dataset.ipynb)) is supposed to download a dataset and save it to a ceph bucket, and the second step ([training.ipynb](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e033cdffeb8291be372417dd2dda819b264aba5c/notebooks/training.ipynb)) is supposed to consume that dataset from the ceph bucket and train a model on it. However, currently the second step notebook just re-downloads the dataset instead of using the pre-saved dataset on ceph.

Functionally this may be fine (doesn’t break anything), but imho it does not accurately showcase the producer-consumer setup and the usefulness of Elyra pipelines. So this could be improved.

Related to #16 

**Acceptance Criterai**
- [ ] update [training.ipynb](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e033cdffeb8291be372417dd2dda819b264aba5c/notebooks/training.ipynb) to consume data from ceph when `TUTORIAL_USE_CEPH=1`, instead of re-downloading data

**Comment by MichaelClifford** [comment]
> So this could be improved.

@chauhankaranraj do you have a suggestion for improvement? Should we add an acceptance criteria like, update traning.ipynb so that it consumes from ceph, instead of re-download data?

**Comment by chauhankaranraj** [comment]
> Should we add an acceptance criteria like, update traning.ipynb so that it consumes from ceph, instead of re-download data?

Yes that sounds good :+1: Also, fwiw the training notebook does have a code snippet for consuming data from ceph, but it's commented out and I'm not exactly sure why :sweat_smile:

**Comment by oindrillac** [comment]
Resolved by https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/197
