### ISSUE TITLE
when inserting URL to meteor shower and click submit, meteor freezes

### ISSUE THREAD

**Issue by pacospace** [AICoE/meteor#230]
**Describe the bug**
when inserting URL to meteor shower and click submit, meteor freezes

**To Reproduce**
1. Go to https://shower.meteor.zone/
2. Submit a URL from a repo (meteor compatible)

**Expected behavior**
meteor builds images.

**Screenshots**
![Screenshot from 2021-11-30 09-52-56](https://user-images.githubusercontent.com/27498679/144015606-738a1364-d1d7-4b8d-aa35-0dad9e88d736.png)

**Additional context**

**Comment by tumido** [comment]
I'll try restarting Shower. Something went bonkers in Smaug and despite having the Role, Rolebinding and ServiceAccount in place for ages and without a change, for some reason Shower is denied to create a Meteor resource in the cluster...

**Comment by tumido** [comment]
I'm about to redeploy Meteor anyways.. so.. lets use it as an opportunity for upgrade. :smile:

**Comment by pacospace** [comment]
> I'm about to redeploy Meteor anyways.. so.. lets use it as an opportunity for upgrade. smile

Happy to test that :D

**Comment by pacospace** [comment]
This was solved with the new deployment.
