### ISSUE TITLE
Time taken to train model in Elyra tutorial

### ISSUE THREAD

**Issue by isabelizimm** [AICoE/meteor#24]
As a new user looking to have a brief intro to the Meteor project, I want a "quick-and-easy" process. When running [training.ipynb](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e033cdffeb8291be372417dd2dda819b264aba5c/notebooks/training.ipynb), the length of time it takes to go through the 10 training epochs is, in my experience, about 10-15 minutes. It may be useful to shorten number of epochs or otherwise find a way to improve the speed of training in this demo.

Related to #16 

Acceptance Criteria:

- [ ] Submit PR to repo decreasing number of epochs from 10 to 1.

**Comment by MichaelClifford** [comment]
:+1: On that note, it looks like you can get about +90% accuracy with 1 epoch. 

![image](https://user-images.githubusercontent.com/4494906/124023598-18516a80-d9bc-11eb-9c02-8627a23d4811.png)


Should we decrease the number of epochs to 1? This should reduce the time by a factor of 10 : )

**Comment by isabelizimm** [comment]
Yes-- that looks like a good way to shorten the time!

**Comment by oindrillac** [comment]
related : #16

**Comment by oindrillac** [comment]
Resolved by https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/197
