### ISSUE TITLE
Spawned repos start with README opened with markdown preview 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#26]
When repos are spawned into jupyter lab environments users should be met with the README.md rendered with the markdown preview tool.  Otherwise, users will just see the launcher, and it might not be immediately obvious how to proceed with the tutorial.

**Comment by tumido** [comment]
Imvestigation needed. Can we parameterize JH spawner request to redirect to a path within the JupyterLab instance immediately after spawning the notebook?

Example:
1. spawning notebook from an URL: https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/hub/spawn?configuration-files-analysis:latest 
2. Redirect to a path within the JupyterLab via relative [`/tree` url](https://jupyterlab.readthedocs.io/en/stable/user/urls.html#file-navigation-with-tree)

Can we include the step no.2 as a parameter of the URL for step no.1?
