### ISSUE TITLE
Remove pre-requsite.md and automate prerequisite set up

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#28]
The environment set up should manage all the prerequisites for the user. So this [doc](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/pre-requisite.md) in its current state should not be required.  

- [ ] Update it to inform the user what is being set up for them, or what existing shared services that are connected to
- [ ] Remove from being step zero in the tutorial list.

**Comment by oindrillac** [comment]
related / duplicate of #22
