### ISSUE TITLE
jupyter-nbrequirements doesnt work for training notebook in Elyra tutorial

### ISSUE THREAD

**Issue by chauhankaranraj** [AICoE/meteor#29]
**Describe the bug**
When trying to update packages for [`training.ipynb`](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/e967491ebb77f83a6a5ba360b5f6516f827080f9/notebooks/training.ipynb) using the jupyter-nbrequirements extension, it gets stuck with a message saying "Contacting thoth for advise... please be patient!".

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
2. Spawn Elyra tutorial image
3. Open `notebooks/training.ipynb`
4. Click on "Manage Dependencies"
5. Add a new dependency and click "+"
6. Click save button and then click Install.

**Expected behavior**
Dependencies get updated

**Screenshots**
![Screenshot from 2021-07-02 15-36-35](https://user-images.githubusercontent.com/15005500/124321274-6e084d00-db4b-11eb-83f8-bcfed3a21237.png)

**Additional context**
Inspecting the pod logs indicates that there is an indentation error in a python file somewhere. After that, the dependency inputs are sent to thoth advisor but the request times out. 
![Screenshot from 2021-07-02 15-37-26](https://user-images.githubusercontent.com/15005500/124321327-80828680-db4b-11eb-8d6c-543929feb283.png)

Related to #16

**Comment by pacospace** [comment]
This is solved already, but new image with jupyterlab-requirements >= 0.7.4 is not available on operate first

**Comment by chauhankaranraj** [comment]
> This is solved already

That's awesome!

> new image with jupyterlab-requirements >= 0.7.4 is not available on operate first

What needs to happen for this? Is it just a matter of creating a new release?

**Comment by pacospace** [comment]
> > This is solved already
> 
> That's awesome!
> 
> > new image with jupyterlab-requirements >= 0.7.4 is not available on operate first
> 
> What needs to happen for this? Is it just a matter of creating a new release?

ODH needs to release a new s2i-lab-elyra image that includes the new s2i-minimal notebook released. cc @harshad16

**Comment by MichaelClifford** [comment]
> ODH needs to release a new s2i-lab-elyra image that includes the new s2i-minimal notebook released. cc @harshad16

Do we have an ETA for when this will happen?

**Comment by pacospace** [comment]
> > ODH needs to release a new s2i-lab-elyra image that includes the new s2i-minimal notebook released. cc @harshad16
> 
> Do we have an ETA for when this will happen?

@harshad16 did we get new jupyterlab-requirements in the new ODH release of the s2i-lab-elyra image?

**Comment by harshad16** [comment]
>did we get new jupyterlab-requirements in the new ODH release of the s2i-lab-elyra image?

i had already released them ,forget to open a pr to odh :sweat: 
https://github.com/opendatahub-io/odh-manifests/pull/455
