### ISSUE TITLE
Provide an example to show the utility of jupyterlab-requirements and overlays

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#30]
I do not think it is immediately obvious to the average data scientist what the benefit of managing dependencies per notebook would be, in contrast to repo-wide dependency management.    

In the step 2 doc `explore-notebooks-and-manage-dependencies.md` we should provide a couple of examples to explain the need and benefit of this additional layer of dependency management. 

two suggestions:

1. If you are going to use KFpipelines you need to have them defined per notebook 
2. Two high level ML packages (say, hatesonar and gensim) rely on different versions of tensorflow.

**Comment by pacospace** [comment]
See: https://github.com/AICoE/overlays-for-ai-pipeline-tutorial
