### ISSUE TITLE
/docs/source/test-model.md should be updated to remove `pip install thamos`

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#31]
https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/180

**Comment by pacospace** [comment]
> [AICoE/elyra-aidevsecops-tutorial#180](https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/180)

thamos comes with jupyterlab-requirements: https://github.com/thoth-station/jupyterlab-requirements/blob/863c5d0df3664981966e4300fb6f0951ddef067b/Pipfile#L11

**Comment by MichaelClifford** [comment]
Should the instructions to install thamos be removed from  `/docs/source/test-model.md` then ?

![image](https://user-images.githubusercontent.com/4494906/124987620-11a1a380-e00b-11eb-92da-f381cd68d750.png)

**Comment by pacospace** [comment]
> Should the instructions to install thamos be removed from `/docs/source/test-model.md` then ?
> 
> ![image](https://user-images.githubusercontent.com/4494906/124987620-11a1a380-e00b-11eb-92da-f381cd68d750.png)

In this case yes, as the base image we use contains that already, as they are s2i-thoth base also.

**Comment by MichaelClifford** [comment]
closed by https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/200
