### ISSUE TITLE
Flowchart visualization providing an overview of the product pipeline

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor#33]
Come up with a flowchart to describe the entire project meteor workflow based on the "crawl" phase of the design doc: https://docs.google.com/document/d/1eCwFJirmAxzAMQRstAbL4Cq0gXX0R2WM9LcBIYYz7lA/edit?usp=sharing

**Comment by hemajv** [comment]
We (@isabelizimm @Shreyanand @aakankshaduggal) have created an initial flowchart diagram here: https://drive.google.com/file/d/12f69NAgCKMaQCOsoQrf52MtFxhCHGEJj/view?usp=sharing and is ready for review.

**Comment by tumido** [comment]
@hemajv I think one step got out of order here and I've added few bits, otherwise it looks great :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/7453394/125261530-a35a2b00-e301-11eb-9385-a2c7425e04c6.png)


1. The AICoE-CI build pipeline creates an image no matter if the user is logged in to JupyterHub or not. This step is not dependent on it.
2. Metrics are collected from build pipelines and spawner etc as well, not just from the ML model
3. AICoE-CI is not creating releases in the data science repo in this case. We can't assume we have write access to the repo.
