### ISSUE TITLE
Document steps for conversion to JupyterBook format

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor#34]
While converting Elyra tutorials document necessary steps.

**Comment by oindrillac** [comment]
We have documented the steps required for creating and publishing a Jupyter Book from a repository here: 

https://docs.google.com/document/d/1fkLko3tG4Na_3UbGA-YzTqU-H42r-cU-skX07luyXho/edit

We have tested the workflow on our forks of the elyra-devsecops-tutorial repo and deployed the site using Github Pages - https://oindrillac.github.io/elyra-aidevsecops-tutorial/README.html and highlighted the parts which need significantautomation
