### ISSUE TITLE
please review your contributor status to this project

### ISSUE THREAD

**Issue by goern** [AICoE/meteor#357]
Hey all, please review your contributor status to this project: if you are still willing to review or approve PR let me know. If you are not willing or able to review or approve PR do nothing.

In the next week I'll open a PR to reconfigure the OWNERS file...

/cc @HumairAK
/cc @durandom
/cc @hemajv
/cc @tumido
/cc @4n4nd
/cc @harshad16
/cc @larsks
/cc @oindrillac
/cc @quaid

**Comment by quaid** [comment]
Not it!

(I.e., thanks for asking, it's fine to remove me as a reviewer for now I reckon.)

**Comment by tumido** [comment]
I haven't mind reviewing so far, but I'm not interested, invested in or attached to the project in any way anymore. If this project is supposed to continue, I think it would be better if more active folks than me would assume the role.

Thanks for raising this issue. 👍

**Comment by goern** [comment]
/close
via #360
