### ISSUE TITLE
automatically populate runtime images and runtime for users setting values in configmaps

### ISSUE THREAD

**Issue by pacospace** [AICoE/meteor#36]
This was done during first workshop of this tutorial with @tumido and @vasek

**Comment by pacospace** [comment]
cc @MichaelClifford, so we can skip some steps of the tutorial. wdyt?

**Comment by tumido** [comment]
Not sure about this.. I think we wanted each Meteor user to input their own URL in Meteor and get their own images. How this one fit in?

/area comet

**Comment by pacospace** [comment]
> Not sure about this.. I think we wanted each Meteor user to input their own URL in Meteor and get their own images. How this one fit in?
> 
> /area comet

what do you mean by their own URL? The Kubefloe Pipeline URL should be discovered automatically by the pipelines populating the environment, so the user does not have to worry or making errors, because the wrong URL of kfp is used or if ceph bucket URL is wrong. Those should be checked initially by the pipeline and eventually fail and provide to users inputs on what to do. "You are requesting a URL for KFP that does not exists" wdyt?

Same for runtime images, we can read the elyra pipeline in the projects and check what runtime images they want, we can create configuration files to be added by the pipelines so user do not have to insert inputs and risk to make mistakes while typing. wdyt?

**Comment by tumido** [comment]
> what do you mean by their own URL?

repository URL, since that's the only expected user input to project Meteor. But that's irrelevant, since I probably missed the point of this issue. :slightly_smiling_face: 

> what do you mean by their own URL? The Kubefloe Pipeline URL should be discovered automatically by the pipelines populating the environment as this run on certain ODH version, so the user does not have to worry or making errors, because the wrong URL of kfp is used or if ceph bucket URL is wrong. Those should be checked initially by the pipeline and eventually fail and provide to users inputs on what to do. "You are requesting a URL for KFP that does not exists" wdyt?

Yup, I certainly misunderstood the issue then, sorry. :slightly_smiling_face:  I agree with that. Can you clarify which configmap are you talking about then? You mean like setting environment variables for JupyterHub pods?

**Comment by tumido** [comment]
This #32 seems like a direct manifestation of what you're talking about, right @pacospace?

**Comment by pacospace** [comment]
> This #32 seems like a direct manifestation of what you're talking about, right @pacospace?

Exactly!!

**Comment by pacospace** [comment]
> > what do you mean by their own URL?
> 
> repository URL, since that's the only expected user input to project Meteor. But that's irrelevant, since I probably missed the point of this issue. 
> 
> > what do you mean by their own URL? The Kubefloe Pipeline URL should be discovered automatically by the pipelines populating the environment as this run on certain ODH version, so the user does not have to worry or making errors, because the wrong URL of kfp is used or if ceph bucket URL is wrong. Those should be checked initially by the pipeline and eventually fail and provide to users inputs on what to do. "You are requesting a URL for KFP that does not exists" wdyt?
> 
> Yup, I certainly misunderstood the issue then, sorry.  I agree with that. Can you clarify which configmap are you talking about then? You mean like setting environment variables for JupyterHub pods?

Don't remember exactly how it was done at the time, need to check. @vpavlin might remember where those changes need to be inserted, so we can make the pipeline set those configuration (runtime and runtime images) for the Elyra image.

**Comment by pacospace** [comment]
> > > what do you mean by their own URL?
> > 
> > 
> > repository URL, since that's the only expected user input to project Meteor. But that's irrelevant, since I probably missed the point of this issue.
> > > what do you mean by their own URL? The Kubefloe Pipeline URL should be discovered automatically by the pipelines populating the environment as this run on certain ODH version, so the user does not have to worry or making errors, because the wrong URL of kfp is used or if ceph bucket URL is wrong. Those should be checked initially by the pipeline and eventually fail and provide to users inputs on what to do. "You are requesting a URL for KFP that does not exists" wdyt?
> > 
> > 
> > Yup, I certainly misunderstood the issue then, sorry.  I agree with that. Can you clarify which configmap are you talking about then? You mean like setting environment variables for JupyterHub pods?
> 
> Don't remember exactly how it was done at the time, need to check. @vpavlin might remember where those changes need to be inserted, so we can make the pipeline set those configuration (runtime and runtime images) for the Elyra image.

Or we can use the elyra CLI to set those also in the assembly script actually during the build process

**Comment by vpavlin** [comment]
> Don't remember exactly how it was done at the time, need to check. @vpavlin might remember where those changes need to be inserted, so we can make the pipeline set those configuration (runtime and runtime images) for the Elyra image.

Well, I had a custom patch to JupyterHub Singleuser Profiles for the workshop which allowed mounting CMs, Secrets and EmptyDir, so that we could pre-generate a CM with the KFP URLs and then just mount it for every user. I don't think we have actually merged that patch, but I can update it and get it merged if you need/want to

**Comment by pacospace** [comment]
> > Don't remember exactly how it was done at the time, need to check. @vpavlin might remember where those changes need to be inserted, so we can make the pipeline set those configuration (runtime and runtime images) for the Elyra image.
> 
> Well, I had a custom patch to JupyterHub Singleuser Profiles for the workshop which allowed mounting CMs, Secrets and EmptyDir, so that we could pre-generate a CM with the KFP URLs and then just mount it for every user. I don't think we have actually merged that patch, but I can update it and get it merged if you need/want to

That would be great @vpavlin!! cc @tumido wdyt?

**Comment by tumido** [comment]
@pacospace @vpavlin that would definitely do for now. :slightly_smiling_face: 

I wonder what is the way looking forward, how can we generalize it for new images, for any image... Is there a way to inject those variables via an API call to JH spawner or something?

**Comment by codificat** [comment]
Doing some issue refining based on my understanding of the history so far (please correct as appropriate):

> I don't think we have actually merged that patch, but I can update it and get it merged if you need/want to

/assign @vpavlin 

> @pacospace @vpavlin that would definitely do for now.

/remove-lifecycle rotten
/triage accepted
