### ISSUE TITLE
Set up Automation Flags in Elyra demo repo

### ISSUE THREAD

**Issue by oindrillac** [AICoE/meteor#40]
As the Open Data Hub platform, I want to set/inject some Notebook Feature Flags via ENV var, so that I declare which environment services can be assumed as available to the execution environment of the notebook

Currently, we have code fragments and import statements in the [notebooks](https://github.com/AICoE/elyra-aidevsecops-tutorial/tree/master/notebooks) which are commented out and uncommented depending on whether we use Ceph for data exchange. 

To avoid the extra manual step of un-commenting code before triggering a Kubeflow pipeline, we can use automation flags as an environment variable which automatically read/write data from and to Ceph when the notebook is running in automation.

**Acceptance Criteria**

- [ ] Modify notebooks in elyra-repo to make it suitable for consuming Automation ENV variables.

/area shooting-star

**Comment by goern** [comment]
how is https://github.com/AICoE/meteor/issues/36 related?

**Comment by pacospace** [comment]
> As the Open Data Hub platform, I want to set/inject some Notebook Feature Flags via ENV var, so that I declare which environment services can be assumed as available to the execution environment of the noteboojk
> 
> Currently, we have code fragments and import statements in the [notebooks](https://github.com/AICoE/elyra-aidevsecops-tutorial/tree/master/notebooks) which are commented out and uncommented depending on whether we use Ceph for data exchange.
> 
> To avoid the extra manual step of un-commenting code before triggering a Kubeflow pipeline, we can use automation flags as an environment variable which automatically read/write data from and to Ceph when the notebook is running in automation.
> 
> **Acceptance Criteria**
> 
> * [ ]  ?
> 
> /area shooting-star

is `USE_CEPH`, not giving the expected purpose? or do we want to have general env variables? e.g. `IS_AUTOMATION`

**Comment by tumido** [comment]
@pacospace what about something from what we have available in JH environment on each pod?

![image](https://user-images.githubusercontent.com/7453394/125303898-70c62780-e32d-11eb-8a89-49e0a8e7e6b0.png)

**Comment by pacospace** [comment]
> @pacospace what about something from what we have available in JH environment on each pod?
> 
> ![image](https://user-images.githubusercontent.com/7453394/125303898-70c62780-e32d-11eb-8a89-49e0a8e7e6b0.png)

So we want to add new defaults for the pod? I like it!!

**Comment by oindrillac** [comment]
> So we want to add new defaults for the pod? I like it!!

Does this mean we will have a pod level env variable like AUTOMATION, and when its set to true, all notebooks default to `USE_CEPH` = True. That would be useful!

> is `USE_CEPH`, not giving the expected purpose? 

We have a `USE_CEPH`, a notebook specific ENV variable, which should serve the purpose of saving data to Ceph. But right now we have an additional step to also go an uncomment the sections in the notebook which use `USE_CEPH` and comment out other sections. So I modified the Acceptance Criteria here to also modify the notebook to make avoid that extra step.

**Comment by tumido** [comment]
I was thinking more in line like.. what about we reuse the variables. Like.. why to define new `USE_CEPH` variable if we can lookup the existing `S3_ENDPOINT_URL`? So if there's an s3 endpoint defined in the env, let's use it, etc. What would you think about that?

**Comment by goern** [comment]
ja, there is a set of ENV injected by OpenShift, which might all be platform (aka ODH) specific, and a bunch of ENV we want the user to provide, right?

**Comment by oindrillac** [comment]
@tumido I like this idea. So we can configure the notebooks to by default read/write from s3 if cloud object storage credentials are available in ENV variables. And we will let the user override this if they wish to run locally.

**Comment by MichaelClifford** [comment]
closed by https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/197
