### ISSUE TITLE
Create flowchart for existing tutorial content to guide edits and content refinement.  

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#41]
Before we start making specific edits to the tutorial content, we need to create an outline for how we want to update the tutorial to meet the needs of project meteor in light of the additional automation we are developing. The first steps to create this outline is to take stock of the existing content and tutorial flow as a flowchart. From there we can more easily, as a group, decide what needs removing/editing or added. And it should make it simpler to communicate these changes with the rest of the group.    

Acceptance Criteria:

- [x] Create flowchart for existing tutorial content
- [x] Put remove/edit/add tags for each step in the chart
- [x] 'edit' and 'add' tags should be as specific as possible, describing the changes that need to be made.

**Comment by pacospace** [comment]
what do we use for creating flowcharts?

**Comment by aakankshaduggal** [comment]
> what do we use for creating flowcharts? 

We used [draw.io](https://app.diagrams.net/) for the flowcharts.

**Comment by pacospace** [comment]
> > what do we use for creating flowcharts?
> 
> We used [draw.io](https://app.diagrams.net/) for the flowcharts.

Thanks @aakankshaduggal 🚀 💯

**Comment by oindrillac** [comment]
Team _shooting_ -⭐️ has drafted a content outline and a flowchart which highlights the proposed content flow and the recommended modifications to the current content in the [tutorial](https://github.com/AICoE/elyra-aidevsecops-tutorial.git) here : https://docs.google.com/spreadsheets/d/1pEIYt8chf-HVIesujlrcKw-m42RY__Ho4bKT1kjmg9Y/edit?usp=sharing. 

This is now ready for review by the rest of the team ☄️
