### ISSUE TITLE
Decide how to build and deploy the static content JupyterBook

### ISSUE THREAD

**Issue by goern** [AICoE/meteor#47]
/kind feature
/priority backlog
/area shooting-star

**Comment by tumido** [comment]
I think we clarified the strategy on the sprint planning. Let me summarize it here:

- Initiate a different build pipeline using the same source repository
- This pipeline runs an s2i build into a nginx/httpd container
- As a middle step during the build process the repo is funneled through `jupyter-book build` and the resulted HTML files are then server by the nginx
- Shower deploys the pod in Meteor namespace + service + route and displays a link to it

wdyt @goern @harshad16 @durandom ?

**Comment by goern** [comment]
I'm unsure about the namespace schema we use for meteor.. otherwise

/lgtm

**Comment by tumido** [comment]
Resolved via: https://github.com/AICoE/meteor-operator/pull/6

We build the repo using s2i httpd container now.
