### ISSUE TITLE
Create s2i image builder can serve jupyterbook HTML content

### ISSUE THREAD

**Issue by harshad16** [AICoE/meteor#48]
This image would help with the meteor workflow in various places.

**Comment by harshad16** [comment]
cc: @tumido @4n4nd @pacospace

**Comment by 4n4nd** [comment]
@harshad16 would this image be similar to the https://github.com/AICoE/s2i-custom-notebook image, so that it can be used as a base image for the subsequent images used in Meteor?

**Comment by harshad16** [comment]
No @4n4nd , it would just a base image with jupyterbook addition :) 
and would be used in the pipeline to run some commands

**Comment by tumido** [comment]
As @harshad16 pointed out. This image will be a builder image with following spec:

1. based on s2i-nginx or s2i-httpd
2. includes additional jupyter-book binary
3. includes a custom assembly script step executing the `jupyter-book build` and moving files around so they the nginx can serve them.

**Comment by tumido** [comment]
Together with @harshad16  we also decided to host this image together with other s2i images in the thoth station, is that correct @harshad16 ?

**Comment by fridex** [comment]
@tumido we have s2i base images with gunicorn that are available and offered by thoth+python maintenance team. I saw you are building the service in go, what is the reason for that?

**Comment by tumido** [comment]
> we have s2i base images with gunicorn that are available and offered by thoth+python maintenance team

In this case we need something that would serve static HTML - this is html is generated from `jupyter-book build` binary. We don't need much python in this case.

> I saw you are building the service in go, what is the reason for that?
@fridex the go service is unrelated to this ticket. Reason for go is that in the next iteration the codebase will be reused and split into a OpenShift operator and a lightweight web service. It's easier to work with kubernetes in golang.

**Comment by harshad16** [comment]
> Together with we also decided to host this image together with other s2i images in the thoth station?

that is correct :+1:

**Comment by tumido** [comment]
Resolved via: https://github.com/AICoE/meteor-operator/pull/6

using HTTPD S2I container
