### ISSUE TITLE
Opting out of tracking

### ISSUE THREAD

**Issue by Shreyanand** [AICoE/meteor#56]
As a user of the Meteor application, I want a choice to opt out of tracking  my content. I may not like my config file changed with an Analytics tracking ID from the Meteor application. 

Discussion

1. How are we planning to inject the tracking ID? 
  - By changing the config at source? The user may not like it and it will add a step of creating a PR at source repository when we have the URL.
  - By changing the config file in the build pipeline? This may lead to multiple source problem, although I'd prefer this since it's more user friendly.

2. What prompt do we want to show users in the beginning and how does the tracking workflow change based on users' choice?

**Comment by Shreyanand** [comment]
@harshad16  For point 1 in discussion, do we have a preferred solution?  Based on the discussion here, we will know how to move ahead with https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/234. I think we should not change the source repository and do everything in our pipelines but I could be wrong.

**Comment by harshad16** [comment]
i agree, we would do it through the pipeline, we can have opt option from the meteor website or from the .aicoe-ci.yaml file.
let keep the discussion for that.

**Comment by hemajv** [comment]
yes I think that's what we have decided. If its going to be via pipelines then we can close https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/234. And we still need to figure out how we want to provide the opt-out option for users

**Comment by tumido** [comment]
Question: doesn't each jupyterbook image render on different domain? Doesn't it also need a different tracking ID? I don't think we should be generating tracking IDs and updating our GA config during th eJupyterBook build.

Technical details if the above doesn't apply and this is not blocked:
1. UI can show a banner/toggle/advanced menu, whatever looks nice that allows you to opt out from injecting tracking into the jupyterbook images.
2. This optional do-not-track attribute is propagated to the `Meteor` resource which in turn gets propagated as a parameter to the `jupyterbook` pipeline.
3. Jupyterbook pipeline has an extra step/task that sets the value in `_config.yaml` before `jupyter-book build`.

**Comment by tumido** [comment]
Bump

**Comment by isabelizimm** [comment]
for devconf.us, we will be adding a disclaimer to the front page of the website to inform users of the information that is being tracked.

**Comment by isabelizimm** [comment]
> for devconf.us, we will be adding a disclaimer to the front page of the website to inform users of the information that is being tracked.

When looking deeper into wording, it looks like "browse wrap" or adding a (non-checkbox) disclaimer is not viable consent to track data on users. I'm not sure I want to implement this approach...WDYT? @aakankshaduggal @tumido @Shreyanand @hemajv

**Comment by tumido** [comment]
yeah.. true.. I don't think we can solve this in time for devconf though.. there's a way to implement consent screen:

https://stackoverflow.com/questions/67220994/allow-google-analytics-to-load-only-after-consented-in-next-js
