### ISSUE TITLE
Identify required Prometheus metrics

### ISSUE THREAD

**Issue by hemajv** [AICoE/meteor#58]
Once we have Prometheus setup (#51), we should check to see what metrics are available and retain/add relevant metrics needed based on those defined [here](https://github.com/AICoE/meteor/blob/main/docs/metrics.md)

**Acceptance Criteria**

- [x] Identify required metrics
- [x] Add any custom metrics required to be included in Prometheus

**Comment by hemajv** [comment]
Some metrics we can look at from an Operations/Technical Architect persona for measuring our pipelines:

- Tekton pipeline metrics - https://tekton.dev/docs/pipelines/metrics/

cc @harshad16 @tumido @pacospace any other metrics apart from those mentioned [here](https://github.com/AICoE/meteor/blob/main/docs/metrics.md), that we would want to consider? We can discuss in this issue and narrow down the metrics so that we can start identifying where we can fetch them

**Comment by hemajv** [comment]
Now that we have configured Prometheus metrics, let's discuss here what we think are the most relevant metrics we should keep
@4n4nd @Shreyanand @isabelizimm @aakankshaduggal @harshad16 @pacospace

**Comment by 4n4nd** [comment]
Suggested Meteor Operator Metrics:
* CRs (`Meteors`) deleted/active
* Deployments/Services/ImageStreams/Routes active/deleted

**Comment by isabelizimm** [comment]
With the previous MOC latency issues in mind, it might be interesting to track latency as well for user experience. :)

**Comment by harshad16** [comment]
| Pipeline | Label | Details |
|------------|---------|-----------|
| tekton_pipelinerun_duration_seconds_[bucket, sum, count] | pipeline={jupyterbook:jupyterhub}, namespace={aicoe-meteor}, status={Running:Succeed:Failed}| |
| tekton_pipelinerun_taskrun_duration_seconds_[bucket, sum, count] | pipeline={jupyterbook:jupyterhub}, namespace={aicoe-meteor}, status={Running:Succeed:Failed}, task={jupyterbook-build-run:notebook-build-run}| |
| tekton_pipelinerun_count | status={Running:Succeed:Failed}| |
| tekton_running_pipelineruns_count | |
| tekton_taskruns_pod_latency | namespace={aicoe-meteor}, status={Running:Succeed:Failed}, task={jupyterbook-build-run:notebook-build-run}| |

**Comment by goern** [comment]
here is a small set of metrics I'd like to see

As a Meteor Service Owner, I would like to have a look at a dashboard,
so that I can see the number of repositories build by meteor,
and so that I can see the number of deployed repositories,
and so that I can see the number of unique users/orgs using meteor
and so that I can see that the number of non-satisfied user requires is below 95%
and so that I can see the total memory and cpu consumption of repos deployed by Meteor

**Comment by tumido** [comment]
to add to the @harshad16 's comment above. Those metrics are available via Openshift Pipelines, those are available always and as a baseline. In addition to that I've consolidated custom metric definitions that we generate during our pipeline runs and push via pushgateway. Here's a list:

https://github.com/AICoE/meteor-operator/blob/163cd9a30b50a5bb05b2a9a33895ef13c2b982c4/config/pipelines/tasks/send-metrics.yaml#L31-L103
