### ISSUE TITLE
Add deep dive into AICoE Pipelines to Meteor Flowchart

### ISSUE THREAD

**Issue by riekrh** [AICoE/meteor#62]
The Meteor flow chart should zoom in on the AICoE Pipelines section and explain what the steps in it are, explain Toth, etc.

https://github.com/AICoE/meteor/blob/main/docs/images/project-flowchart.png

**Comment by hemajv** [comment]
We have added an in-depth view of the AICoE pipelines in the flowchart here: https://app.diagrams.net/#G1AW6nTpTbdmZ3r8ymIpke2VoqE3OJlKYu

![Screenshot from 2021-08-05 16-26-36](https://user-images.githubusercontent.com/7343099/128416527-8fc7e515-36a8-4829-afc7-ff707727695e.png)

**Comment by Shreyanand** [comment]
@harshad16 @tumido If there's anything missing or incorrect here, we can iterate on this. Thanks for laying it out for us :)

**Comment by durandom** [comment]
@hemajv @Shreyanand for the metrics: I would a prometheus server and google analytics to the side and just point arrows to the boxes where you're scraping metrics from. Like in the architecture at https://github.com/prometheus/prometheus

**Comment by aakankshaduggal** [comment]
Sure thing @durandom! We will add this as well.
