### ISSUE TITLE
Configure Google Analytics for upstream Elyra tutorial/Meteor web page

### ISSUE THREAD

**Issue by hemajv** [AICoE/meteor#64]
After successfully testing and setting up GA for one of our forks of the Elyra tutorial (#50), we should now configure GA for the upstream Elyra tutorial and/or Meteor webpage

**Acceptance Criteria**

- [x] Setup GA for Meteor webpage
- [ ] Setup GA for upstream Elyra tutorial
- [x] GA dashboard to visualize metrics

**Comment by hemajv** [comment]
We are wondering if we need to have GA tag configured with the Elyra tutorial and Meteor web page separately or if it would be possible to have the GA tag configured with just the Meteor web page and this should automatically also fetch data for the rendered Elyra tutorial Jupyter book? 

@tumido any thoughts on which way we should go about this? (based on how the Meteor web page + Jupyter book will be built)

**Comment by hemajv** [comment]
Yes, we tested it out for the Jupyter book by adding a GA tag in the `config.yaml` [here](https://github.com/Shreyanand/elyra-aidevsecops-tutorial/blob/master/_config.yml#L24) and it works!

So I guess it narrows down to deciding between benefits of having separate tags or just one tag, which depends on answering some following questions:

- Can the Jupyterbook be reachable separately i.e. without logging in via the Meteor web page? If yes, then we will need to have separate tags for the Meteor web page and the Jupyterbook
- Are we are only concerned with knowing how many users visited the tutorial via the Meteor web page? If yes, then having just one tag should suffice

**Comment by Shreyanand** [comment]
> Yes, we tested it out for Shrey's fork of the Elyra Jupyter book by adding a GA tag in the `config.yaml` [here](https://github.com/Shreyanand/elyra-aidevsecops-tutorial/blob/master/_config.yml#L24) and it works!
> 
> So I guess it narrows down to deciding between benefits of having separate tags or just one tag, which depends on answering some following questions:
> 
> * Can the Elyra Jupyterbook be reachable separately i.e. without logging in via the Meteor web page? If yes, then we will need 
to have separate tags for the Meteor web page and the Jupyterbook

That should be the case, right? Once the pipelines generate a link for the book, it should remain there unless redeployed...

> * Are we are only concerned with the users who visited the Elyra tutorial via the Meteor web page? If yes, then having just one tag should suffice

If we have information for all the users who visited the tutorial, we could separate the user views that came from meteor and the ones that came from other sources through the referrals data that GA collects. IMO both of them have value: how many users are here through the tutorial app and how many users came back again on their own to use the book. WDYT?

**Comment by tumido** [comment]
GA for Meteor Shower works:
![image](https://user-images.githubusercontent.com/7453394/128384934-4f45fa7b-5e01-4c04-b56a-0474f5cd73d7.png)

https://analytics.google.com/analytics/web/#/p281781571/reports/reportinghub

Using GA4 (the new gtag)

**Comment by hemajv** [comment]
We have a GA dashboard for the Meteor Shower app here: https://datastudio.google.com/reporting/5115a591-f004-4e5f-88e2-d38cc2d26561 
thanks @isabelizimm :partying_face:
